MODEL:
  EXTRA:
    FINAL_CONV_KERNEL: 1
    PRETRAINED_LAYERS: ['*']
    STEM_INPLANES: 64
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      - 128
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      - 128
      - 256
      FUSE_METHOD: SUM
    DECONV:
      NUM_DECONVS: 1
      NUM_CHANNELS:
      - 32
      KERNEL_SIZE:
      - 4
      NUM_BASIC_BLOCKS: 4
      CAT_OUTPUT:
      - True
  INIT_WEIGHTS: True
  NAME: pose_higher_hrnet
  NUM_JOINTS: 17
  PRETRAINED: 'models/pytorch/imagenet/hrnet_w32-36af842e.pth'
  TAG_PER_JOINT: True
DATASET:
  INPUT_SIZE: 512
  NUM_JOINTS: 17
  MAX_NUM_PEOPLE: 30
TEST:
  FLIP_TEST: False
  IMAGES_PER_GPU: 1
  MODEL_FILE: 'HPEstimation/HRNET/checkpoints/pose_higher_hrnet_w32_512.pth' 
  SCALE_FACTOR: [1]
  DETECTION_THRESHOLD: 0.1
  WITH_HEATMAPS: (True, True)
  WITH_AE: (True, False)
  PROJECT2IMAGE: True
  NMS_KERNEL: 5
  NMS_PADDING: 2
LOSS:
  WITH_AE_LOSS: [True, False]
  WITH_HEATMAPS_LOSS: [True, True]
